############################
## HUGO MODULES
## Install or uninstall themes and plugins here.
## Docs: https://gohugo.io/hugo-modules/
############################

imports:
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind
    mounts:
      - source: assets
        target: assets
      - source: data
        target: data
      - source: i18n
        target: i18n
      - source: layouts
        target: layouts
        excludeFiles:
          - _default/_markup/sitemap.xml
      - source: static
        target: static
  - path: github.com/hugomods/icons/vendors/bootstrap
  - path: github.com/hugomods/icons/vendors/font-awesome

# Install any Hugo Blox within the `hugo-blox/blox/` folder
mounts:
  - source: hugo-blox/blox/community
    target: layouts/partials/blox/community/
    includeFiles: '**.html'
  - source: hugo-blox/blox/all-access
    target: layouts/partials/blox/
    includeFiles: '**.html'
  - source: hugo-blox/blox
    target: assets/dist/community/blox/
    includeFiles: '**.css'
  - source: layouts
    target: layouts
  - source: assets
    target: assets
